# Generated by Django 5.0.4 on 2024-04-22 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugname', models.TextField(max_length=50, null=True)),
                ('batchno', models.CharField(default='A1', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medtype', models.TextField(max_length=50)),
                ('manufacturer', models.TextField(max_length=50)),
                ('stockqty', models.IntegerField()),
                ('expriedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(blank=True, null=True, upload_to='medicineImages/')),
            ],
        ),
    ]
