# Generated by Django 5.0.4 on 2024-04-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='expriedate',
            new_name='expirydate',
        ),
    ]
