# Generated by Django 5.0.4 on 2024-04-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_expriedate_medicine_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(default='Enter Description', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medtype',
            field=models.CharField(default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stockqty',
            field=models.IntegerField(default=15),
        ),
    ]
