# Generated by Django 5.0.4 on 2024-04-24 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_medicine_description_alter_medicine_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expirydate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
