# Generated by Django 5.0.4 on 2024-04-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_medicine_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='drugname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
