# Generated by Django 5.0.4 on 2024-05-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Date_of_Birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='profile',
            name='PermanentAddress',
            field=models.TextField(default='Permanent Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='TempAddress',
            field=models.TextField(default='Temporary Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bloodGroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='displayName',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='+1234567890', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Worker', 'Worker'), ('Owner', 'Owner'), ('Admin', 'Admin')], default='Customer', max_length=10),
        ),
    ]
