# Generated by Django 5.0.4 on 2024-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile_date_of_birth_profile_permanentaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='UserImages\\default.jpg', upload_to='UserImages/'),
        ),
    ]
