# Generated by Django 5.0.4 on 2024-05-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='end_date',
            field=models.DateField(verbose_name='2025-02-09'),
        ),
    ]
