# Generated by Django 5.0.4 on 2024-05-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_insurance_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='end_date',
            field=models.DateField(default='2025-02-09'),
        ),
    ]
